name: do_app
description: Do App Flutter Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^1.3.0
  fluttertoast: ^8.0.9
  hive: ^2.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3


flutter:

  uses-material-design: true
